name: ml-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - xgboost
  - catboost
  - lightgbm
  - pip
  - pip:
    - -r requirements.txt